 mysql:
  image: mysql
  container_name: mysql_owncloud
  ports:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=owncloud
   - MYSQL_USER=owncloud
   - MYSQL_PASSWORD=password
 hosts:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
   - 80:80
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
 owncloud:
  image: owncloud:8.1
  container_name: owncloud
  links:
   - mysql
  ports:
    - "8002:80"
  environment:
    - VIRTUAL_HOST=owncloud.localhost
  volumes:
    - /var/www/owncloud:/var/www/html
